version: '3.9'
services:
  web:
    build:
      context: ./infrastructure/web
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./infrastructure/app/Dockerfile
    volumes:
      - .:/app
    expose:
      - 9000
